"""
Rich profile seeder for Mana Vivaha (మన వివాహ)
Generates high-quality First Marriage and Second Marriage (పునర్వివాహం) profiles
with authentic Telugu details, verified photos, real districts, and complete compatibility data.
"""
import json
from datetime import datetime

SECOND_MARRIAGE_PROFILES = [
    {
        "tsap_id": "MV2001",
        "gender": "Bride",
        "full_name": "Sowmya Reddy",
        "age": 30,
        "dob": "1996-05-14",
        "height": "5'4\"",
        "weight": "55kg",
        "caste": "Reddy",
        "sub_caste": "Motati",
        "gothram": "Janakula",
        "star": "Uttara",
        "rasi": "Kanya",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "BTech (CSE)",
        "education_detail": "Computer Science & Engineering",
        "job": "Senior Software Engineer",
        "company": "TCS (Tata Consultancy Services)",
        "salary": "18.5L",
        "experience": "8 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Venkat Reddy",
        "father_occupation": "Agriculture & Business",
        "mother_name": "Radha Reddy",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Nalgonda",
        "state": "TS",
        "district": "Nalgonda",
        "mandal": "Miryalaguda",
        "current_city": "Hyderabad",
        "pincode": "508207",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Fair",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "IT లో సీనియర్ సాఫ్ట్‌వేర్ ఇంజనీర్‌గా స్థిరపడ్డాను. గత వివాహం పరస్పర అంగీకారంతో (mutual consent) చట్టబద్ధంగా ముగిసింది. పిల్లలు లేరు. పరస్పర గౌరవం, మంచి మనసున్న తోడు కోసం చూస్తున్నాం.",
        "expectations": "సాఫ్ట్‌వేర్ లేదా ప్రభుత్వ ఉద్యోగం ఉన్న సంస్కారవంతమైన వరుడు కావాలి. కుటుంబ విలువలకి ప్రాధాన్యత ఇచ్చేవారై ఉండాలి.",
        "phone": "9848011223",
        "photo_urls": ["/promo/bride-card.jpg"]
    },
    {
        "tsap_id": "MV2002",
        "gender": "Groom",
        "full_name": "Rajesh Kamma",
        "age": 33,
        "dob": "1993-08-20",
        "height": "5'10\"",
        "weight": "72kg",
        "caste": "Kamma",
        "sub_caste": "Chowdary",
        "gothram": "Vallutla",
        "star": "Swati",
        "rasi": "Tula",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MS (USA) / BTech",
        "education_detail": "Computer Science",
        "job": "Staff Software Architect",
        "company": "Microsoft",
        "salary": "32L",
        "experience": "10 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Narayana Chowdary",
        "father_occupation": "Retired Govt Officer",
        "mother_name": "Lakshmi Devi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Moderate",
        "native_place": "Vijayawada",
        "state": "AP",
        "district": "Krishna",
        "mandal": "Vijayawada Urban",
        "current_city": "Hyderabad",
        "pincode": "520002",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Fair",
        "blood_group": "B+",
        "children": "1 బాబు (Mother Custody)",
        "about_myself": "Microsoft లో స్టాఫ్ ఆర్కిటెక్ట్‌గా పనిచేస్తున్నాను. లీగల్ డివోర్స్ ప్రక్రియ పూర్తయింది. ఒక బాబు (తల్లి వద్ద ఉన్నాడు). జీవితాన్ని ఆనందంగా, పరస్పర నమ్మకంతో ముందుకు సాగించే జీవిత భాగస్వామి కావాలి.",
        "expectations": "ఉన్నత విద్యావంతురాలైన వధువు కావాలి. జాబ్ లేదా ప్రొఫెషనల్ బ్యాక్‌గ్రౌండ్ ఉంటే ఆహ్వానిస్తాం.",
        "phone": "9989022334",
        "photo_urls": ["/promo/groom-kamma.jpg"]
    },
    {
        "tsap_id": "MV2003",
        "gender": "Bride",
        "full_name": "Dr. Madhavi Varma",
        "age": 32,
        "dob": "1994-03-11",
        "height": "5'5\"",
        "weight": "58kg",
        "caste": "Raju",
        "sub_caste": "Kshatriya",
        "gothram": "Vasishta",
        "star": "Rohini",
        "rasi": "Vrishabha",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MBBS, MD (Pediatrics)",
        "education_detail": "Pediatric Medicine",
        "job": "Consultant Pediatrician",
        "company": "Apollo Hospitals",
        "salary": "24L",
        "experience": "7 years",
        "work_type": "Private Job",
        "work_location": "Visakhapatnam",
        "father_name": "Dr. Rama Raju",
        "father_occupation": "Senior Doctor",
        "mother_name": "Saraswathi Devi",
        "mother_occupation": "Housewife",
        "brothers": "0",
        "brothers_married": "0",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Rich",
        "family_values": "Traditional",
        "native_place": "Visakhapatnam",
        "state": "AP",
        "district": "Visakhapatnam",
        "mandal": "Visakhapatnam Urban",
        "current_city": "Visakhapatnam",
        "pincode": "530002",
        "marital_status": "Widow",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Very Fair",
        "blood_group": "A+",
        "children": "1 పాప (5 yrs)",
        "about_myself": "వైజాగ్ అపోలో హాస్పిటల్ లో పీడియాట్రీషియన్‌గా చేస్తున్నాను. దురదృష్టవశాత్తు భర్త ప్రమాదంలో చనిపోయారు. 5 ఏళ్ల పాప ఉంది. పాపను సొంత బిడ్డలా ఆదరించే, సంస్కారవంతమైన జీవిత భాగస్వామి కోసం చూస్తున్నాం.",
        "expectations": "డాక్టర్ లేదా ఉన్నత ఉద్యోగంలో ఉన్న సంస్కారవంతమైన వరుడు కావాలి.",
        "phone": "9440133445",
        "photo_urls": ["/promo/bride-kapu.jpg"]
    },
    {
        "tsap_id": "MV2004",
        "gender": "Groom",
        "full_name": "Sudhakar Rao Velama",
        "age": 36,
        "dob": "1990-11-05",
        "height": "5'11\"",
        "weight": "76kg",
        "caste": "Velama",
        "sub_caste": "Padmanayaka",
        "gothram": "Recharla",
        "star": "Punarvasu",
        "rasi": "Karka",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MTech",
        "education_detail": "Civil & Structural Engineering",
        "job": "Executive Engineer (Irrigation)",
        "company": "Govt of Telangana",
        "salary": "16L",
        "experience": "12 years",
        "work_type": "Govt Job",
        "work_location": "Warangal",
        "father_name": "Kishan Rao",
        "father_occupation": "Retired DSP Police",
        "mother_name": "Sunitha",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Warangal",
        "state": "TS",
        "district": "Warangal",
        "mandal": "Hanamkonda",
        "current_city": "Warangal",
        "pincode": "506001",
        "marital_status": "Widower",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Wheatish",
        "blood_group": "O+",
        "children": "1 బాబు (7 yrs)",
        "about_myself": "తెలంగాణ ప్రభుత్వ నీటిపారుదల శాఖలో గెజిటెడ్ ఎగ్జిక్యూటివ్ ఇంజనీర్‌గా పనిచేస్తున్నాను. 3 ఏళ్ల క్రితం భార్య అనారోగ్యంతో మరణించారు. 7 ఏళ్ల బాబు ఉన్నాడు. కుటుంబాన్ని, బాబును ప్రేమగా చూసుకునే మంచి మనసున్న జీవిత భాగస్వామి కావాలి.",
        "expectations": "కుటుంబ బాధ్యతలను గౌరవించే సుగుణవంతురాలైన వధువు కావాలి.",
        "phone": "9849244556",
        "photo_urls": ["/promo/groom-vysya.jpg"]
    },
    {
        "tsap_id": "MV2005",
        "gender": "Bride",
        "full_name": "Sandhya Vysya",
        "age": 29,
        "dob": "1997-02-18",
        "height": "5'3\"",
        "weight": "52kg",
        "caste": "Arya Vysya",
        "sub_caste": "Arya Vysya",
        "gothram": "Upamanyu",
        "star": "Hasta",
        "rasi": "Kanya",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "CA (Chartered Accountant) / BCom",
        "education_detail": "Chartered Accountancy",
        "job": "Senior Finance Manager",
        "company": "Deloitte India",
        "salary": "22L",
        "experience": "6 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Satyanarayana Gupta",
        "father_occupation": "Wholesale Business",
        "mother_name": "Venkata Lakshmi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "0",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Joint",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Guntur",
        "state": "AP",
        "district": "Guntur",
        "mandal": "Guntur Urban",
        "current_city": "Hyderabad",
        "pincode": "522002",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Fair",
        "blood_group": "B+",
        "children": "None",
        "about_myself": "డెలాయిట్ హైదరాబాద్ లో సీనియర్ ఫైనాన్స్ మేనేజర్ (CA). గత వివాహం 3 నెలల్లోనే ముగిసింది, లీగల్ డివోర్స్ ఆర్డర్ చేతిలో ఉంది. పిల్లలు లేరు. పరస్పర అవగాహన గల ఉన్నత విద్యావంతుడైన వరుడు కావాలి.",
        "expectations": "CA / Software / Business లో స్థిరపడిన ఆర్యవైశ్య వరుడు కావాలి.",
        "phone": "9949355667",
        "photo_urls": ["/promo/cine-1.jpg"]
    },
    {
        "tsap_id": "MV2006",
        "gender": "Groom",
        "full_name": "Venkatesh Kapu",
        "age": 34,
        "dob": "1992-09-12",
        "height": "5'9\"",
        "weight": "70kg",
        "caste": "Kapu",
        "sub_caste": "Telaga",
        "gothram": "Kasyapa",
        "star": "Uttarabhadra",
        "rasi": "Meena",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MBA / BTech",
        "education_detail": "Product Strategy",
        "job": "Senior Product Manager",
        "company": "Amazon",
        "salary": "28L",
        "experience": "11 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Surya Rao",
        "father_occupation": "Agriculture & Business",
        "mother_name": "Parvathi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Modern",
        "native_place": "Rajahmundry",
        "state": "AP",
        "district": "East Godavari",
        "mandal": "Rajahmundry Urban",
        "current_city": "Hyderabad",
        "pincode": "533101",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Wheatish",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "అమెజాన్ హైదరాబాద్ లో సీనియర్ ప్రాడక్ట్ మేనేజర్‌గా పనిచేస్తున్నాను. పరస్పర అవగాహనతో ముగిసిన గత వివాహం. పిల్లలు లేరు. ఉన్నత ఆలోచనలు గల జీవిత భాగస్వామి కోసం చూస్తున్నాం.",
        "expectations": "ఉద్యోగం లేదా వ్యాపారం చేసే విద్యావంతురాలైన వధువు కావాలి.",
        "phone": "9618466778",
        "photo_urls": ["/promo/story-1.jpg"]
    },
    {
        "tsap_id": "MV2007",
        "gender": "Bride",
        "full_name": "Anuradha Padmashali",
        "age": 31,
        "dob": "1995-06-25",
        "height": "5'4\"",
        "weight": "54kg",
        "caste": "Padmashali",
        "sub_caste": "Padmashali",
        "gothram": "Markandeya",
        "star": "Revati",
        "rasi": "Meena",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MSc, BEd",
        "education_detail": "Mathematics",
        "job": "Govt High School Teacher",
        "company": "Govt of Telangana",
        "salary": "8.5L",
        "experience": "7 years",
        "work_type": "Govt Job",
        "work_location": "Karimnagar",
        "father_name": "Shankaraiah",
        "father_occupation": "Retired Employee",
        "mother_name": "Kamala",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "0",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Karimnagar",
        "state": "TS",
        "district": "Karimnagar",
        "mandal": "Karimnagar",
        "current_city": "Karimnagar",
        "pincode": "505001",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Fair",
        "blood_group": "A+",
        "children": "None",
        "about_myself": "తెలంగాణ ప్రభుత్వ ఉపాధ్యాయురాలిగా పనిచేస్తున్నాను. లీగల్ డివోర్స్ పూర్తయింది. పిల్లలు లేరు. మంచి కుటుంబ విలువలని గౌరవించే ప్రభుత్వ లేదా ప్రైవేట్ ఉద్యోగి కావాలి.",
        "expectations": "ఉద్యోగంలో స్థిరపడిన పద్మశాలి లేదా ఇతర సంబంధాలు ఆహ్వానిస్తాం.",
        "phone": "9701577889",
        "photo_urls": ["/promo/cine-2.jpg"]
    },
    {
        "tsap_id": "MV2008",
        "gender": "Groom",
        "full_name": "Dr. Karthik Sharma",
        "age": 35,
        "dob": "1991-04-10",
        "height": "5'10\"",
        "weight": "74kg",
        "caste": "Brahmin",
        "sub_caste": "Niyogi",
        "gothram": "Kaundinya",
        "star": "Arudra",
        "rasi": "Mithuna",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "BDS, MDS (Orthodontics)",
        "education_detail": "Orthodontics & Dental Surgery",
        "job": "Clinic Director & Consultant",
        "company": "Sri Sai Dental Speciality Hospital",
        "salary": "26L",
        "experience": "9 years",
        "work_type": "Business",
        "work_location": "Tirupati",
        "father_name": "Panchangam Viswanatha Sarma",
        "father_occupation": "Vedic Scholar & Astrologer",
        "mother_name": "Bhavani",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Joint",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Tirupati",
        "state": "AP",
        "district": "Tirupati",
        "mandal": "Tirupati Urban",
        "current_city": "Tirupati",
        "pincode": "517501",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Fair",
        "blood_group": "AB+",
        "children": "None",
        "about_myself": "తిరుపతిలో సొంత డెంటల్ క్లినిక్ మరియు కన్సల్టెంట్‌గా ఉన్నాను. కుటుంబంలో వైదిక సంప్రదాయాలు ఉన్నాయి. గత వివాహం పరస్పర అంగీకారంతో ముగిసింది. పిల్లలు లేరు.",
        "expectations": "సంస్కారవంతమైన బ్రాహ్మణ వధువు కావాలి.",
        "phone": "9848688990",
        "photo_urls": ["/promo/story-2.jpg"]
    },
    {
        "tsap_id": "MV2009",
        "gender": "Bride",
        "full_name": "Kavitha Munnuru Kapu",
        "age": 30,
        "dob": "1996-01-19",
        "height": "5'3\"",
        "weight": "56kg",
        "caste": "Munnuru Kapu",
        "sub_caste": "Munnuru Kapu",
        "gothram": "Kasyapa",
        "star": "Anuradha",
        "rasi": "Vrischika",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MCA",
        "education_detail": "Computer Applications",
        "job": "Data Analyst",
        "company": "Cognizant",
        "salary": "12L",
        "experience": "7 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Narsimha Patel",
        "father_occupation": "Business",
        "mother_name": "Sujatha",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Nizamabad",
        "state": "TS",
        "district": "Nizamabad",
        "mandal": "Nizamabad",
        "current_city": "Hyderabad",
        "pincode": "503001",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Wheatish",
        "blood_group": "O+",
        "children": "1 బాబు (3 yrs)",
        "about_myself": "హైదరాబాద్ లో డేటా అనలిస్ట్‌గా చేస్తున్నాను. 3 ఏళ్ల బాబు ఉన్నాడు. కుటుంబ బాధ్యతలు తెలిసిన, బాబుని ఆదరించే మంచి మనసున్న వరుడు కావాలి.",
        "expectations": "మంచి ఉద్యోగం ఉన్న మున్నూరు కాపు లేదా ఇతర సంబంధాలు కావాలి.",
        "phone": "9440799001",
        "photo_urls": ["/promo/cine-3.jpg"]
    },
    {
        "tsap_id": "MV2010",
        "gender": "Groom",
        "full_name": "Prasad Goud",
        "age": 36,
        "dob": "1990-07-14",
        "height": "5'8\"",
        "weight": "68kg",
        "caste": "Goud",
        "sub_caste": "Goud",
        "gothram": "Gautama",
        "star": "Moola",
        "rasi": "Dhanu",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "BTech",
        "education_detail": "Electrical Engineering",
        "job": "Senior Manager (SBI)",
        "company": "State Bank of India",
        "salary": "15L",
        "experience": "11 years",
        "work_type": "Govt Job",
        "work_location": "Khammam",
        "father_name": "Mallaiah Goud",
        "father_occupation": "Agriculture",
        "mother_name": "Sathyavathi",
        "mother_occupation": "Housewife",
        "brothers": "2",
        "brothers_married": "2",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Khammam",
        "state": "TS",
        "district": "Khammam",
        "mandal": "Khammam Urban",
        "current_city": "Khammam",
        "pincode": "507001",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Wheatish",
        "blood_group": "B+",
        "children": "None",
        "about_myself": "స్టేట్ బ్యాంక్ ఆఫ్ ఇండియాలో సీనియర్ మేనేజర్‌గా చేస్తున్నాను. గత వివాహం ముగిసింది, పిల్లలు లేరు. ప్రశాంతమైన జీవితం కోసం మంచి సంబంధం చూస్తున్నాం.",
        "expectations": "ఉపాధ్యాయురాలు లేదా ఉద్యోగం చేసే గౌడ్ వధువు కావాలి.",
        "phone": "9848122334",
        "photo_urls": ["/promo/story-3.jpg"]
    },
    {
        "tsap_id": "MV2011",
        "gender": "Bride",
        "full_name": "Dr. Shailaja Yadav",
        "age": 33,
        "dob": "1993-10-02",
        "height": "5'5\"",
        "weight": "57kg",
        "caste": "Yadav",
        "sub_caste": "Golla",
        "gothram": "Atri",
        "star": "Chitra",
        "rasi": "Kanya",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MD (General Medicine)",
        "education_detail": "General Medicine",
        "job": "Assistant Professor / Govt Medical College",
        "company": "Govt Medical College, Kurnool",
        "salary": "20L",
        "experience": "8 years",
        "work_type": "Govt Job",
        "work_location": "Kurnool",
        "father_name": "Govind Yadav",
        "father_occupation": "Retired Govt Teacher",
        "mother_name": "Padmavathi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Kurnool",
        "state": "AP",
        "district": "Kurnool",
        "mandal": "Kurnool Urban",
        "current_city": "Kurnool",
        "pincode": "518002",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Fair",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "కర్నూలు ప్రభుత్వ వైద్య కళాశాలలో అసిస్టెంట్ ప్రొఫెసర్‌గా పనిచేస్తున్నాను. డివోర్స్ పూర్తయింది. పిల్లలు లేరు. పరస్పర అవగాహన గల డాక్టర్ లేదా గెజిటెడ్ ఆఫీసర్ సంబంధం కావాలి.",
        "expectations": "డాక్టర్ లేదా ప్రొఫెషనల్ వరుడు కావాలి.",
        "phone": "9391233445",
        "photo_urls": ["/promo/cine-4.jpg"]
    },
    {
        "tsap_id": "MV2012",
        "gender": "Groom",
        "full_name": "Srinivas Reddy (NRI USA)",
        "age": 35,
        "dob": "1991-08-30",
        "height": "6'0\"",
        "weight": "78kg",
        "caste": "Reddy",
        "sub_caste": "Pakanati",
        "gothram": "Bharadwaj",
        "star": "Sravana",
        "rasi": "Makara",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MS in AI/CS (USA)",
        "education_detail": "Artificial Intelligence & Cloud",
        "job": "AI Principal Engineer (USA)",
        "company": "Tech Giant, Dallas, Texas",
        "salary": "1.4 Cr ($165k)",
        "experience": "11 years",
        "work_type": "Private Job",
        "work_location": "USA / Dallas, Texas",
        "father_name": "Raghava Reddy",
        "father_occupation": "Agriculture & Real Estate",
        "mother_name": "Sumathi Reddy",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Nuclear",
        "family_status": "Rich",
        "family_values": "Moderate",
        "native_place": "Hyderabad",
        "state": "TS",
        "district": "Hyderabad",
        "mandal": "Gachibowli",
        "current_city": "USA / Dallas",
        "pincode": "500032",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Fair",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "USA లో AI ప్రిన్సిపల్ ఇంజనీర్‌గా స్థిరపడ్డాను (Green Card track). గత వివాహం mutual consent తో పూర్తయింది. పిల్లలు లేరు. USA కి రీలోకేట్ అవ్వడానికి సిద్ధంగా ఉన్న అర్థం చేసుకునే తోడు కావాలి.",
        "expectations": "Software / BTech / MS వధువు కావాలి. USA ప్రయాణం పట్ల ఆసక్తి ఉండాలి.",
        "phone": "9849555666",
        "photo_urls": ["/promo/story-4.jpg"]
    },
    {
        "tsap_id": "MV2013",
        "gender": "Bride",
        "full_name": "Sunitha Madiga",
        "age": 31,
        "dob": "1995-12-08",
        "height": "5'4\"",
        "weight": "53kg",
        "caste": "SC",
        "sub_caste": "Madiga",
        "gothram": "Gautama",
        "star": "Ashwini",
        "rasi": "Mesha",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MSc Chemistry, BEd",
        "education_detail": "Organic Chemistry",
        "job": "Degree College Lecturer",
        "company": "Govt Degree College",
        "salary": "7.5L",
        "experience": "6 years",
        "work_type": "Govt Job",
        "work_location": "Mahabubnagar",
        "father_name": "Venkaiah",
        "father_occupation": "Retired Govt Official",
        "mother_name": "Satyamma",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Mahabubnagar",
        "state": "TS",
        "district": "Mahabubnagar",
        "mandal": "Mahabubnagar",
        "current_city": "Mahabubnagar",
        "pincode": "509001",
        "marital_status": "Widow",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Wheatish",
        "blood_group": "B+",
        "children": "1 బాబు (Mother Custody)",
        "about_myself": "డిగ్రీ కళాశాలలో లెక్చరర్‌గా పనిచేస్తున్నాను. వితంతువు. ఒక బాబు ఉన్నాడు. సమానత్వం మరియు గౌరవం ఇచ్చే మంచి సంబంధం కోరుకుంటున్నాం.",
        "expectations": "ప్రభుత్వ లేదా స్థిరపడిన ప్రైవేట్ ఉద్యోగం గల వరుడు కావాలి.",
        "phone": "9703444555",
        "photo_urls": ["/dp-tsbride.png"]
    },
    {
        "tsap_id": "MV2014",
        "gender": "Groom",
        "full_name": "Mahesh Balija",
        "age": 34,
        "dob": "1992-05-18",
        "height": "5'9\"",
        "weight": "71kg",
        "caste": "Balija",
        "sub_caste": "Setty Balija",
        "gothram": "Vasishta",
        "star": "Krittika",
        "rasi": "Vrishabha",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "BTech",
        "education_detail": "Information Technology",
        "job": "Senior Tech Lead",
        "company": "Infosys",
        "salary": "21L",
        "experience": "11 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Subba Rao",
        "father_occupation": "Business",
        "mother_name": "Rajeswari",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Upper Middle",
        "family_values": "Traditional",
        "native_place": "Nellore",
        "state": "AP",
        "district": "Nellore",
        "mandal": "Nellore Urban",
        "current_city": "Hyderabad",
        "pincode": "524001",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Fair",
        "blood_group": "A+",
        "children": "None",
        "about_myself": "ఇన్ఫోసిస్ లో టెక్ లీడ్‌గా చేస్తున్నాను. లీగల్ డివోర్స్ పూర్తయింది. పిల్లలు లేరు. స్నేహపూర్వక మనస్తత్వం ఉన్న జీవిత భాగస్వామి కావాలి.",
        "expectations": "విద్యావంతురాలైన బలిజ లేదా కాపు వధువు కావాలి.",
        "phone": "9848777888",
        "photo_urls": ["/dp-tsgroom1.png"]
    },
    {
        "tsap_id": "MV2015",
        "gender": "Bride",
        "full_name": "Farzana Begum",
        "age": 29,
        "dob": "1997-04-12",
        "height": "5'4\"",
        "weight": "54kg",
        "caste": "Muslim",
        "sub_caste": "Syed",
        "gothram": "None",
        "star": "Hasta",
        "rasi": "Kanya",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Muslim",
        "mother_tongue": "Urdu / Telugu",
        "education": "MPharm",
        "education_detail": "Pharmacy & Clinical Research",
        "job": "Quality Assurance Lead",
        "company": "Dr. Reddy's Laboratories",
        "salary": "11L",
        "experience": "6 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Mohammed Abdul Khadar",
        "father_occupation": "Retired Govt Employee",
        "mother_name": "Shabana Begum",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "0",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Hyderabad",
        "state": "TS",
        "district": "Hyderabad",
        "mandal": "Charminar",
        "current_city": "Hyderabad",
        "pincode": "500002",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Fair",
        "blood_group": "B+",
        "children": "None",
        "about_myself": "Bismillahir Rahmanir Raheem. డాక్టర్ రెడ్డీస్ ల్యాబ్స్ లో క్వాలిటీ అస్యూరెన్స్ లీడ్‌గా పనిచేస్తున్నాను. చట్టబద్ధంగా విడాకులు పూర్తయ్యాయి. పిల్లలు లేరు. దీన్ మరియు దునియా రెండింటినీ గౌరవించే సున్నీ వరుడు కావాలి.",
        "expectations": "Sunni Muslim well-settled groom.",
        "phone": "9849888999",
        "photo_urls": ["/promo/bride-card.jpg"]
    },
    {
        "tsap_id": "MV2016",
        "gender": "Groom",
        "full_name": "David John",
        "age": 33,
        "dob": "1993-03-22",
        "height": "5'11\"",
        "weight": "73kg",
        "caste": "Christian",
        "sub_caste": "CSI Protestant",
        "gothram": "None",
        "star": "Swati",
        "rasi": "Tula",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Christian",
        "mother_tongue": "Telugu",
        "education": "MBA / BCom",
        "education_detail": "Banking & Finance",
        "job": "Branch Operations Head",
        "company": "HDFC Bank",
        "salary": "14L",
        "experience": "9 years",
        "work_type": "Private Job",
        "work_location": "Guntur",
        "father_name": "Rev. John Wesley",
        "father_occupation": "Church Pastor",
        "mother_name": "Mary Grace",
        "mother_occupation": "Teacher",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Guntur",
        "state": "AP",
        "district": "Guntur",
        "mandal": "Guntur Urban",
        "current_city": "Guntur",
        "pincode": "522001",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Fair",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "In the Name of Jesus Christ. హెచ్‌డిఎఫ్‌సి బ్యాంకులో బ్రాంచ్ ఆపరేషన్స్ హెడ్‌గా పనిచేస్తున్నాను. లీగల్ డివోర్స్ పూర్తయింది. దైవభక్తి, కుటుంబ విలువలు ఉన్న క్రైస్తవ వధువు కావాలి.",
        "expectations": "Christian CSI / Catholic / Baptist bride with good values.",
        "phone": "9440999000",
        "photo_urls": ["/promo/groom-kamma.jpg"]
    },
    {
        "tsap_id": "MV2017",
        "gender": "Bride",
        "full_name": "Haritha Mudiraj",
        "age": 32,
        "dob": "1994-08-14",
        "height": "5'3\"",
        "weight": "55kg",
        "caste": "Mudiraj",
        "sub_caste": "Mudiraj",
        "gothram": "Kasyapa",
        "star": "Pushya",
        "rasi": "Karka",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "BTech",
        "education_detail": "Electronics & Communication",
        "job": "Quality Engineer",
        "company": "Tech Mahindra",
        "salary": "10L",
        "experience": "8 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Bikshapathi Mudiraj",
        "father_occupation": "Agriculture",
        "mother_name": "Laxmi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Medak",
        "state": "TS",
        "district": "Medak",
        "mandal": "Medak",
        "current_city": "Hyderabad",
        "pincode": "502110",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Fair",
        "blood_group": "A+",
        "children": "None",
        "about_myself": "సాఫ్ట్‌వేర్ క్వాలిటీ ఇంజనీర్‌గా స్థిరపడ్డాను. డివోర్స్ పూర్తయింది, పిల్లలు లేరు. బాధ్యత గల జీవిత భాగస్వామి కావాలి.",
        "expectations": "ముదిరాజ్ లేదా ఇతర సాఫ్ట్‌వేర్/ప్రభుత్వ ఉద్యోగి కావాలి.",
        "phone": "9848222111",
        "photo_urls": ["/promo/bride-kapu.jpg"]
    },
    {
        "tsap_id": "MV2018",
        "gender": "Groom",
        "full_name": "Suresh Boya",
        "age": 35,
        "dob": "1991-02-28",
        "height": "5'9\"",
        "weight": "70kg",
        "caste": "Boya",
        "sub_caste": "Valmiki",
        "gothram": "Valmiki",
        "star": "Magha",
        "rasi": "Simha",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MA, BEd",
        "education_detail": "Telugu Literature & Teaching",
        "job": "Govt High School Headmaster",
        "company": "Govt of AP",
        "salary": "11.5L",
        "experience": "10 years",
        "work_type": "Govt Job",
        "work_location": "Anantapur",
        "father_name": "Ramappa Boya",
        "father_occupation": "Farmer",
        "mother_name": "Gowramma",
        "mother_occupation": "Housewife",
        "brothers": "2",
        "brothers_married": "2",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Nuclear",
        "family_status": "Middle Class",
        "family_values": "Traditional",
        "native_place": "Anantapur",
        "state": "AP",
        "district": "Anantapur",
        "mandal": "Anantapur Urban",
        "current_city": "Anantapur",
        "pincode": "515001",
        "marital_status": "Widower",
        "physical_status": "Normal",
        "body_type": "Average",
        "complexion": "Wheatish",
        "blood_group": "B+",
        "children": "1 బాబు (6 yrs)",
        "about_myself": "ప్రభుత్వ ఉన్నత పాఠశాల ప్రధానోపాధ్యాయుడిగా పనిచేస్తున్నాను. భార్య గతించింది. ఒక బాబు ఉన్నాడు. కుటుంబ విలువలని గౌరవించే మంచి సంబంధం కావాలి.",
        "expectations": "ఉపాధ్యాయురాలు లేదా ఉద్యోగం చేసే వధువు కావాలి.",
        "phone": "9440111222",
        "photo_urls": ["/promo/groom-vysya.jpg"]
    },
    {
        "tsap_id": "MV2019",
        "gender": "Bride",
        "full_name": "Swapna Kamma",
        "age": 31,
        "dob": "1995-11-15",
        "height": "5'5\"",
        "weight": "56kg",
        "caste": "Kamma",
        "sub_caste": "Chowdary",
        "gothram": "Vallutla",
        "star": "Uttara",
        "rasi": "Kanya",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MS (USA) / BTech",
        "education_detail": "Data Science & Cloud",
        "job": "Senior Data Scientist",
        "company": "Amazon AWS",
        "salary": "25L",
        "experience": "8 years",
        "work_type": "Private Job",
        "work_location": "Hyderabad",
        "father_name": "Nageswara Rao Chowdary",
        "father_occupation": "Real Estate & Business",
        "mother_name": "Sita Mahalakshmi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "0",
        "sisters_married": "0",
        "family_type": "Nuclear",
        "family_status": "Rich",
        "family_values": "Moderate",
        "native_place": "Guntur",
        "state": "AP",
        "district": "Guntur",
        "mandal": "Guntur Urban",
        "current_city": "Hyderabad",
        "pincode": "522006",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Slim",
        "complexion": "Fair",
        "blood_group": "O+",
        "children": "None",
        "about_myself": "AWS హైదరాబాద్ లో సీనియర్ డేటా సైంటిస్ట్‌గా పనిచేస్తున్నాను. mutual consent డివోర్స్. పిల్లలు లేరు. కెరీర్ మరియు ఫ్యామిలీ రెండింటినీ అర్థం చేసుకునే కమ్మ వరుడు కావాలి.",
        "expectations": "IT / MS (USA) / Business వరుడు కావాలి.",
        "phone": "9848555444",
        "photo_urls": ["/promo/cine-1.jpg"]
    },
    {
        "tsap_id": "MV2020",
        "gender": "Groom",
        "full_name": "Chaitanya Varma",
        "age": 35,
        "dob": "1991-09-04",
        "height": "5'11\"",
        "weight": "75kg",
        "caste": "Raju",
        "sub_caste": "Kshatriya",
        "gothram": "Vasishta",
        "star": "Punarvasu",
        "rasi": "Mithuna",
        "moola_nakshatram": "No",
        "dosham": "No",
        "religion": "Hindu",
        "mother_tongue": "Telugu",
        "education": "MTech",
        "education_detail": "Structural Engineering",
        "job": "Managing Director",
        "company": "Varma Infra & Constructions",
        "salary": "35L",
        "experience": "11 years",
        "work_type": "Business",
        "work_location": "Visakhapatnam",
        "father_name": "Bhupathi Raju",
        "father_occupation": "Business & Industrialist",
        "mother_name": "Vijaya Lakshmi",
        "mother_occupation": "Housewife",
        "brothers": "1",
        "brothers_married": "1",
        "sisters": "1",
        "sisters_married": "1",
        "family_type": "Joint",
        "family_status": "Rich",
        "family_values": "Traditional",
        "native_place": "Visakhapatnam",
        "state": "AP",
        "district": "Visakhapatnam",
        "mandal": "Visakhapatnam Urban",
        "current_city": "Visakhapatnam",
        "pincode": "530003",
        "marital_status": "Divorced",
        "physical_status": "Normal",
        "body_type": "Athletic",
        "complexion": "Fair",
        "blood_group": "B+",
        "children": "None",
        "about_myself": "వైజాగ్ లో సొంత కన్‌స్ట్రక్షన్ కంపెనీ నడుపుతున్నాను. పరస్పర సమ్మతితో డివోర్స్ పూర్తయింది. పిల్లలు లేరు. ప్రశాంతమైన జీవితం, ఉన్నత కుటుంబ నేపథ్యం గల వధువు కావాలి.",
        "expectations": "క్షత్రియ / రాజు సంస్కారవంతమైన వధువు కావాలి.",
        "phone": "9989444333",
        "photo_urls": ["/promo/groom-kamma.jpg"]
    }
]

def generate_full_database():
    import seed_launch_db
    
    # Generate 55 fresh first marriage profiles
    base_profiles = seed_launch_db.build_profiles(count=55, seed=777)
    
    # Standardize first marriage profiles
    clean_profiles = []
    
    # Add our crafted Second Marriage profiles first with top quality
    for p in SECOND_MARRIAGE_PROFILES:
        p["is_verified"] = True
        p["phone_verified"] = True
        p["is_approved"] = True
        p["plan"] = "FREE"
        p["credits"] = 3
        p["seed_source"] = "second_marriage_special"
        p["created_at"] = datetime.utcnow().isoformat()
        p["referral_code"] = p["full_name"][:3].upper() + "20"
        p["referral_alias"] = f"MV-REF-{p['tsap_id']}"
        p["referral_link"] = f"https://manavivaha.in/r/{p['referral_code']}"
        p["referral_tier"] = "BRONZE"
        p["referral_stats"] = {"total": 0, "earned": 0, "clicks": 0, "registrations": 0, "paid_count": 0, "wallet": 0, "lifetime_earned": 0, "pending_payout": 0, "paid_out": 0, "paid_today": 0, "paid_today_date": "", "tier": "BRONZE", "milestones_hit": [], "flags": []}
        p["credit_history"] = []
        p["card_url"] = f"/cards/{p['tsap_id']}.png"
        p["phone_encrypted"] = f"enc_{p['phone'][-4:]}"
        clean_profiles.append(p)
    
    # Add first marriage profiles with short clean MV IDs and real photo URLs
    photo_brides = ["/promo/bride-card.jpg", "/promo/bride-kapu.jpg", "/promo/cine-1.jpg", "/promo/cine-2.jpg", "/promo/cine-3.jpg", "/promo/cine-4.jpg", "/dp-tsbride.png"]
    photo_grooms = ["/promo/groom-kamma.jpg", "/promo/groom-vysya.jpg", "/promo/story-1.jpg", "/promo/story-2.jpg", "/promo/story-3.jpg", "/promo/story-4.jpg", "/dp-tsgroom1.png"]
    
    for idx, u in enumerate(base_profiles):
        mv_id = f"MV1{idx+1:03d}"
        u["tsap_id"] = mv_id
        u["marital_status"] = "Never Married"
        u["children"] = "None"
        u["is_verified"] = True
        u["phone_verified"] = True
        u["is_approved"] = True
        
        # Attach photo
        if u["gender"] == "Bride":
            u["photo_urls"] = [photo_brides[idx % len(photo_brides)]]
        else:
            u["photo_urls"] = [photo_grooms[idx % len(photo_grooms)]]
            
        u["referral_code"] = (u["full_name"].split()[0][:3] if u.get("full_name") else "USR").upper() + f"{idx+10:02d}"
        u["referral_alias"] = f"MV-REF-{mv_id}"
        u["referral_link"] = f"https://manavivaha.in/r/{u['referral_code']}"
        u["referral_tier"] = "BRONZE"
        u["referral_stats"] = {"total": 0, "earned": 0, "clicks": 0, "registrations": 0, "paid_count": 0, "wallet": 0, "lifetime_earned": 0, "pending_payout": 0, "paid_out": 0, "paid_today": 0, "paid_today_date": "", "tier": "BRONZE", "milestones_hit": [], "flags": []}
        u["credit_history"] = []
        u["card_url"] = f"/cards/{mv_id}.png"
        u["phone_encrypted"] = f"enc_{str(u.get('phone', '9999'))[-4:]}"
        clean_profiles.append(u)
        
    db_payload = {
        "saved_at": datetime.utcnow().isoformat(),
        "users": clean_profiles,
        "interests": [],
        "payments": [],
        "otps": {},
        "verified_phones": [],
        "views": [],
        "saves": [],
        "digest": []
    }
    
    with open("backend/data_db.json", "w", encoding="utf-8") as f:
        json.dump(db_payload, f, ensure_ascii=False, indent=2)
        
    print(f"✅ Successfully wrote {len(clean_profiles)} profiles to backend/data_db.json")
    print(f"   💍 Second Marriage Profiles: {len(SECOND_MARRIAGE_PROFILES)}")
    print(f"   👰 First Marriage Profiles: {len(base_profiles)}")

if __name__ == "__main__":
    generate_full_database()
